### ISSUE TITLE
Scrollbar vertical height & theming

### ISSUE THREAD

**Issue by lexicalunit** [fv0/native-ui#29]
See here:

<img width="530" alt="screen shot 2015-12-16 at 2 33 24 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853183/0dcf3222-a402-11e5-86c6-e6e683149f6e.png">

It looks like the scrollbar extends a bit too far in the vertical directions here. See how it interrupts the bottom line of the tab and the top line of the status bar? It also stands out quite a bit compared to the solarized syntax theme I'm using (as well as any theme with a non-white background). I think this is mostly due to the fact that the scrollbar comes between the text editor and the minimap. One workaround for this is to enable absolute mode on the minimap:

<img width="302" alt="screen shot 2015-12-16 at 2 47 23 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853492/f1068db4-a403-11e5-9889-aa1f9554a381.png">

Which looks better (still the vertical extension of the scrollbar is an issue though), but also means that text will occasionally be underneath the minimap.

It would also be possible to adapt the scrollbar's theme to the user's syntax theme like the [isotope-ui](https://atom.io/themes/isotope-ui) and [isotope-light-ui](https://atom.io/themes/isotope-light-ui) themes do. For example:

<img width="324" alt="screen shot 2015-12-16 at 2 41 16 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853424/7b08e67a-a403-11e5-9592-51fb248c259d.png">
<img width="483" alt="screen shot 2015-12-16 at 2 39 22 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853425/7b0af42e-a403-11e5-87b0-0ad04b4809c1.png">
<img width="485" alt="screen shot 2015-12-16 at 2 38 48 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853423/7b06bb70-a403-11e5-866a-8e9eb5a4453d.png">

This way the scrollbar doesn't stand out so much, because the background on the text editor area blends seamlessly with the background of the minimap. But I recognize this solution doesn't really jive with the whole "Native UI" ideal. Here's what Xcode does for comparison:

<img width="230" alt="screen shot 2015-12-16 at 2 43 41 pm" src="https://cloud.githubusercontent.com/assets/1903876/11853593/8bf9ed48-a404-11e5-8e26-fda2c1c877a6.png">

Notice the line of the tab unbroken as it passes over the scrollbar. However, the panes directly right of the scrollbar are lightly colored so it isn't as jarring a transition as in Atom with the minimap.

**Comment by fv0** [comment]
Thanks for taking the time to write your detailed thoughts. This is what the scrollbar looks like on my display. In this case I don't know how to reproduce the scrollbar overlap which you have to be able to fix this. If you can help me out on this I can see what I can do.

<img width="398" alt="screen shot 2015-12-18 at 16 01 05" src="https://cloud.githubusercontent.com/assets/8401092/11899731/672ccec4-a5a1-11e5-98da-02e9f6867542.png">

The scrollbar is also the standard scrollbar you have in OSX and even though there are `::-webkit` selectors to target scrollbars I am not going to touch them. They stand out visually in comparison to the Solarized syntax theme, but for another person who uses a light syntax theme it might blend in perfectly. There's no "one design fits all" approach for this.

If you have the hardware I'd suggest you activate this in your System Preferences → General:

<img width="411" alt="screen shot 2015-12-18 at 16 10 55" src="https://cloud.githubusercontent.com/assets/8401092/11899813/0847301a-a5a2-11e5-86f8-1aa01eb2ec3c.png">

The tabs adapting to the background color in isotope-ui is very neat indeed but it will really break the "native" approach to mimic OSX' surface design. That's why it will not happen. Maybe in another theme in the future?

**Comment by lexicalunit** [comment]
Oh man, I wonder what's going on with my scroll bars. Let me try and disable some packages and comment out stuff in my `styles.less` and see if I can figure it out.

**Comment by lexicalunit** [comment]
So I deleted my `~/.atom` directory and started up Atom 1.3.2. I installed only the Native UI theme and the minimap package. The vertical extension of the scrollbar only really stands out for some syntax themes, particularly the lighter ones:

With One Dark, there doesn't seem to be an issue:
![one-dark](https://cloud.githubusercontent.com/assets/1903876/11904492/1c118c10-a586-11e5-96e8-b41f18630ee6.png)

However with Solarized Light, we see the issue:
![solarized-light](https://cloud.githubusercontent.com/assets/1903876/11904491/1c0f2470-a586-11e5-9a74-801c53d3a189.png)

I actually see the issue on all the Light syntax themes that Atom comes packaged with.

**Comment by lexicalunit** [comment]
Here's the issue with lighter syntax themes zoomed in:
![zoom](https://cloud.githubusercontent.com/assets/1903876/11905401/f7a97184-a58b-11e5-96c2-5b6bd9c8ab77.png)

The issue seems to be the 1px inside bevel just between the tab bar and the editing area. You can clearly see this in the following light themes:
- Atom Light
- Base16 Tomorrow Light
- One Light
- Solarized Light

This 1px bevel actually exists in dark themes too, but it's harder to see it so visually you don't notice it. Here's a zoomed in view of the screenshot you posted in your previous comment in this thread:
![yours](https://cloud.githubusercontent.com/assets/1903876/11905583/e5bbe8ca-a58c-11e5-8972-46f2fa2bbeec.png)

The bevel exists there too :scream: 

In Xcode, that line (or bevel) whatever you want to call it, extends past the scrollbar. It's easy to see here, even without zooming in:
![xcode](https://cloud.githubusercontent.com/assets/1903876/11905644/31aaf758-a58d-11e5-9747-0bb0d532bede.png)

Incidentally, setting OS X's scrollbars to show only when scrolling is a neat workaround &mdash; but it affects the entire system, not just Atom :cry:
![hide scrollbars](https://cloud.githubusercontent.com/assets/1903876/11905674/5a93c118-a58d-11e5-8be4-d371d2dc20ce.png)

IMHO, if it's possible, Native UI should extend that line/bevel so that it passes over (and under) the scrollbars. This would be matching what Xcode does so it would totally be in line with making Native UI as "native" as possible :smile:
