### ISSUE TITLE
Match OS X tab-dragging behavior

### ISSUE THREAD

**Issue by akivajgordon** [fv0/native-ui#49]
Might be out of the scope of this project, but is there a way to get OS X's native tab-dragging behavior in the mix? That is, when dragging a tab, it:
- only moves horizontally, regardless of cursor's vertical movement
- pushes the adjacent tab into its original space to make room for the new drop location as soon as the cursor crosses the adjacent tab's boundary (with animation)
- _does not_ show a green (+) indicator
- _does not_ show a blue border between the adjacent tab

As seen in Safari, Finder, Terminal, etc. tabs.

**Comment by jamesplease** [comment]
The drag behavior when the mouse remains near the tab bar seems doable. I'm curious to know if it's possible to emulate the behavior when you drag a Finder tab far away :) My guess is that it isn't tho (transforming the 'ghost image' like that seems like it'd be a real challenge)

**Comment by akivajgordon** [comment]
I would say that the tear-away behavior that you mention would be a real bonus, but I'd be most interested in the behavior that I originally enumerated.

**Comment by jamesplease** [comment]
> but I'd be most interested in the behavior that I originally enumerated.

Same 👌 

I might slowly, slowly work on this. I'll be posting any updates I have in this comment.

The first thing is the "green plus" that appears when dragging. This is because something somewhere is turning the `cursor` to be `copy`. It's not in the `tabs` package, so...the search continues. I don't think that it's default webkit behavior, but maybe?

**Update:** the cursor behavior seems to be default webkit behavior. Some evidence for that.
1. [a demo from MDN](http://mdn.github.io/drag-and-drop/copy-move-DataTransfer.html) showing it, and [its source](https://github.com/mdn/drag-and-drop/blob/gh-pages/copy-move-DataTransfer.html).
2. [An SO question](http://stackoverflow.com/questions/10119514/html5-drag-drop-change-icon-cursor-while-dragging) that seems to be talking about this, with pretty complex solutions

**Comment by fv0** [comment]
Thanks for the efforts. I'd always keep in in mind if this little feature is really worth the potential performance downturns and if it behaves fluid and smooth. At the end you need the editor to be a reliant workhorse for code. But go for it, I'd like to at least see it :wink:

**Comment by fv0** [comment]
Just stumbled across this: https://github.com/atom/tabs/pull/252
Currently in Atom 1.9.0-beta0 → http://blog.atom.io/2016/06/06/atom-1-8-and-1-9-beta.html

**Comment by jamesplease** [comment]
Based on the above behavior, I think this issue can be closed. I agree that emulating the native behavior is best when possible, but in this case I don't think it's worth losing the layout management behavior.

What do others think?
